import Head from 'next/head'
import { Inter } from 'next/font/google'

import Sidenav from '@/components/Sidenav'
import Main from '@/components/Main'
import Work from '@/components/Work'
import Projects from '@/components/Projects'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Sidenav />
          <Main />
          <Work />
          <Projects />
        </div>
      </main>
    </>
  )
}
