import React from "react";
import Workitem from "./Workitem";

const data = [
  {
    year: 2018,
    title: "Softel",
    duration: "5 Years",
    description:
      "Data scientist developer:\n\n Identifying patterns and data distribution to add value to information across different projects.\n \
      Implementing algorithms for anomaly detection in tabular data.\n  \
      Relocating devices with imprecise GPS information using ML models.\n Developing predictive models for estimating CO2 generated by refrigerators.\n Generating clusters to optimize node placement \
      for the Wi-Sun network.\n Experimenting with YOLO for computer vision system demos.\n Prototyping with Monte Carlo algorithm to estimate the volume of silos.\n\n \
      Backend developer:\n\n Design architecture to develop different projects.\n Implementing services to feed front-end. Functions to preprocesing and processing information. \
      Implementing pipelines  of ETL",
  },
  {
    year: 2014,
    title: "Instituto Interdisciplinario de las Ciencias",
    duration: "2 Years",
    description:
      "Junior Researcher:\n\n Design and implementation of position controllers.\n Simulations with the Monte Carlo algorithm to generate porous surfaces with quantum ",
  },
];

const Work = () => {
  return (
    <div
      id="work"
      className="pt-10 bg-gradient-to-tr h-auto w-screen sm:h-screen bg-fixed bg-cover bg-center from-[#e7e4e4] to-[#abb3cd]"
    >
      <div className="max-w-[1240px] m-auto pl-10 pr-10  ">
        <h1 className="text-4xl p-10 font-bold text-center text-[#e99401]">
          Work
        </h1>
        {data.map((item, idx) => (
          <Workitem
            key={idx}
            year={item.year}
            title={item.title}
            duration={item.duration}
            description={item.description}
          />
        ))}
      </div>
    </div>
  );
};

export default Work;
