import React from "react";
import Workitem from "./Workitem";

const data = [
  {
    year: 2018,
    title: "Softel",
    duration: "5 Years",
    description:
      "Data scientist - Backend developer: Identifying patterns and data distribution to add value to information across different projects. Implementing algorithms for anomaly detection in tabular data. Relocating devices with imprecise GPS information using ML models. Developing predictive models for estimating CO2 generated by refrigerators. Generating clusters to optimize node placement for the Wi-Sun network. Experimenting with YOLO for computer vision system demos. Prototyping with Monte Carlo algorithm to estimate the volume of silos.",
  },
  {
    year: 2014,
    title: "Instituto Interdisciplinario de las Ciencias",
    duration: "2 Years",
    description:
      "Junior Researcher: Design and implementation of position controllers. Simulations with the Monte Carlo algorithm to generate porous surfaces with quantum ",
  },
];

const Work = () => {
  return (
    <div
      id="work"
      className="max-w-[1240px] m-auto pl-10 pr-10 md:pl-20 p-4 py-16"
    >
      <h1 className="text-4xl pt-10 font-bold text-center text-[#e99401]">
        Work
      </h1>
      {data.map((item, idx) => (
        <Workitem
          key={idx}
          year={item.year}
          title={item.title}
          duration={item.duration}
          description={item.description}
        />
      ))}
    </div>
  );
};

export default Work;
