import React from "react";
import Workitem from "./Workitem";

const data = [
  {
    year: 2018,
    title: "Softel",
    duration: "5 Years",
    description:
      "Data scientist developer:  As a data scientist developer, I used statistical and programming skills to analyze data, create predictive models, \
      and solve complex problems using machine learning techniques.\n\n Identifying patterns and data distribution to add value to information across different \
      projects.\n Implementing algorithms for anomaly detection in tabular data.\n Relocating devices with imprecise GPS information\
      using ML models.\n Developing predictive models for estimating CO2 generated by refrigerators.\n Generating clusters to optimize node placement \
      for the Wi-Sun network.\n Experimenting with YOLO for computer vision system demos.\n Prototyping with Monte Carlo algorithm to estimate the \
      volume of silos.\n\nBackend developer: As a backend developer, I designed and built the back-end architecture of web and mobile applications, \
      including services, functions, and data pipelines.\n\n Design architecture to develop different projects.\n Implementing services to feed front-end.\n Functions\
      to preprocesing and processing information.\n Implementing pipelines  of ETL",
  },
  {
    year: 2014,
    title: "Instituto Interdisciplinario de las Ciencias",
    duration: "2 Years",
    description:
      "Junior Researcher: As a Junior Researcher, I contributed to the design and implementation of controllers to regulate the position of objects in a system, \
      and conducted simulations to study the behavior of porous surfaces at the quantum level.\n\n Design and implementation of position controllers.\n Simulations with the Monte Carlo algorithm to generate porous surfaces with quantum ",
  },
];

const Work = () => {
  return (
    <div
      id="work"
      className="pt-14 bg-gradient-to-tr h-auto w-screen bg-fixed bg-cover bg-center from-[#b7b6b6] to-[#abb3cd]"
    >
      <div className="max-w-[1240px] m-auto pl-10 pr-10  ">
        <h1 className="text-4xl pt-10 font-bold text-center text-white">
          Work
        </h1>
        {data.map((item, idx) => (
          <Workitem
            key={idx}
            year={item.year}
            title={item.title}
            duration={item.duration}
            description={item.description}
          />
        ))}
      </div>
    </div>
  );
};

export default Work;
